export const INDEX_FIELD = {
  CANONICAL_CODE: 0,
  DISPLAY_CODE: 1,
  NAME_ZH: 2,
  PINYIN_FULL: 3,
  PINYIN_ABBR: 4,
  ALIASES: 5,
  MARKET: 6,
  ASSET_TYPE: 7,
  ACTIVE: 8,
  POPULARITY: 9,
} as const;

export const MATCH_SCORE = {
  EXACT_MIN: 96,
  PREFIX_MIN: 77,
  CONTAINS_MIN: 57,
  FUZZY_MIN: 1,
} as const;

export const SEARCH_CONFIG = {
  DEFAULT_LIMIT: 10,
  DEBOUNCE_MS: 200,
  MIN_QUERY_LENGTH: 2,
  ACTIVE_ONLY: true,
} as const;
